split_bills/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('split_bills_app.urls')),
]

split_bills_app/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views, models


urlpatterns = [
    path('', views.HouseListView.as_view(), name='house-list'),
    path('house/create', views.HouseCreateView.as_view(), name='house-create'),
    path('house/<int:pk>/update', views.HouseUpdateView.as_view(), name='house-update'),
    path('house/<int:pk>/delete', views.HouseDeleteView.as_view(), name='house-delete'),
   
    path('residents/', views.ResidentsListView.as_view(), name='residents-list'),
    path('residents/create', views.ResidentsCreateView.as_view(), name='residents-create'),
    path('residents/<int:pk>/update', views.ResidentsUpdateView.as_view(), name='residents-update'),
    path('residents/<int:pk>/delete', views.ResidentsDeleteView.as_view(), name='residents-delete'),

    path('billtype/', views.BillTypeListView.as_view(), name='bill-type-list'),
    path('billtype/create', views.BillTypeCreateView.as_view(), name='bill-type-create'),
    path('billtype/<int:pk>/update', views.BillTypeUpdateView.as_view(), name='bill-type-update'),
    path('billtype/<int:pk>/delete', views.BillTypeDeleteView.as_view(), name='bill-type-delete'),

    path('bills/', views.BillsListView.as_view(), name='bills-list'),
    path('bills/create', views.BillsCreateView.as_view(), name='bills-create'),
    path('bills/<int:pk>/update', views.BillsUpdateView.as_view(), name='bills-update'),
    path('bills/<int:pk>/delete', views.BillsDeleteView.as_view(), name='bills-delete'),

    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('register/', views.RegisterPage.as_view(), name='register'),
]

split_bills_app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.contrib.auth.models import User


class BillType(models.Model):
    cod_bill_type = models.AutoField(primary_key=True)
    name = models.CharField(blank=True, null=True, max_length=100, db_column='type')

    class Meta:
        db_table = 'bill_type'
        managed = True
    
    def __str__(self):
        return self.name

class House(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, db_column='user_id')
    cod_house = models.AutoField(primary_key=True)
    adress = models.CharField(max_length=255)
    nick_name = models.CharField(blank=True, null=True, max_length=100)

    class Meta:      
        db_table = 'house'
    
    def __str__(self):
        return self.nick_name    


class Bills(models.Model):
    cod_bills = models.AutoField(primary_key=True)
    name = models.CharField(blank=True, null=True, max_length=100)
    amount = models.TextField(blank=True, null=True)  # This field type is a guess.
    dead_line = models.DateField(blank=True, null=True)
    attachment = models.BinaryField(blank=True, null=True)
    paid_day = models.DateField(blank=True, null=True)
    cod_house = models.ForeignKey(House, models.DO_NOTHING, db_column='cod_house')
    dt_from = models.DateField(blank=True, null=True)
    dt_to = models.DateField(blank=True, null=True)
    cod_bill_type = models.ForeignKey(BillType, models.DO_NOTHING, db_column='cod_bill_type')
    send = models.BooleanField(blank=True, null=True)
    mime_type_old = models.CharField(blank=True, null=True, max_length=10)
    mime_type_res = models.CharField(blank=True, null=True, max_length=10)
    mime_type_99 = models.CharField(db_column='MIME_TYPE_99', blank=True, null=True, max_length=10)  # Field name made lowercase.
    mime_type = models.CharField(blank=True, null=True, max_length=10)

    class Meta:
        db_table = 'bills'
        verbose_name_plural = 'Bills'
    
    def __str__(self):
        return self.name
 
 
class Residents(models.Model):
    cod_resident = models.AutoField(primary_key=True)
    name = models.CharField(blank=True, null=True, max_length=255)
    couple = models.BooleanField(blank=True, null=True)
    email = models.CharField(blank=True, null=True, max_length=100)
    mobile = models.CharField(blank=True, null=True, max_length=100)
    cod_house = models.ForeignKey(to=House, on_delete=models.PROTECT, db_column='cod_house', verbose_name='House')
    dt_in = models.DateField(blank=True, null=True)
    dt_out = models.DateField(blank=True, null=True)

    class Meta:
        db_table = 'residents'
        verbose_name_plural = 'Residents'
    
    def __str__(self):
        return self.name
    
class Split(models.Model):
    cod_split = models.AutoField(primary_key=True)
    amount = models.FloatField(blank=True, null=True)  # This field type is a guess.
    split_date = models.DateField(blank=True, null=True)
    payed_day = models.DateField(blank=True, null=True)
    cod_bills = models.ForeignKey(Bills, models.DO_NOTHING, db_column='cod_bills')
    cod_resident = models.ForeignKey(Residents, models.DO_NOTHING, db_column='cod_resident')

    class Meta:
        db_table = 'split'
    
    def __str__(self):
        return self.cod_split

split_bills_app/views.py
from django.views.generic import ListView, UpdateView, CreateView, DeleteView, FormView
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import render, redirect

from .models import House, Residents, BillType, Bills, Split

#Accounts Views
class RegisterPage(FormView):
    template_name = 'split_bills_app/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('house-list')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)
  
      
class LoginView(LoginView):
    template_name = 'split_bills_app/login.html'    

#House Views
class HouseListView(LoginRequiredMixin, ListView):
    model = House
    template_name = 'split_bills_app/house-list.html'
    context_object_name = 'houses'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["houses"] = context["houses"].filter(user=self.request.user)
        return context
    
    def get_queryset(self):
        return House.objects.filter(user=self.request.user)
    

class HouseCreateView(LoginRequiredMixin, CreateView):
    model = House
    template_name = "split_bills_app/create.html"
    fields = ['nick_name','adress']
    success_url = reverse_lazy('house-list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(HouseCreateView, self).form_valid(form)


class HouseUpdateView(LoginRequiredMixin, UpdateView):
    model = House
    template_name = "split_bills_app/update.html"
    fields = ['nick_name', 'adress']
    context_object_name = 'house'
    def get_success_url(self):
        return reverse_lazy('house-list')

class HouseDeleteView(LoginRequiredMixin, DeleteView):
    model = House
    template_name = "split_bills_app/delete.html"
    success_url = reverse_lazy('house-list')

#Residents Views
class ResidentsListView(LoginRequiredMixin, ListView):
    model = Residents
    template_name = 'split_bills_app/residents-list.html'

class ResidentsCreateView(LoginRequiredMixin, CreateView):
    model = Residents
    template_name = "split_bills_app/create.html"
    fields = ('name','email','mobile','cod_house','dt_in','dt_out')
    success_url = reverse_lazy('residents-list')

class ResidentsUpdateView(LoginRequiredMixin, UpdateView):
    model = Residents
    template_name = "split_bills_app/update.html"
    fields = ('name','email','mobile','cod_house','dt_in','dt_out')
    context_object_name = 'residents'
    def get_success_url(self):
        return reverse_lazy('residents-list')

class ResidentsDeleteView(LoginRequiredMixin, DeleteView):
    model = Residents
    template_name = "split_bills_app/delete.html"
    success_url = reverse_lazy('residents-list')

#Bill Type Views
class BillTypeListView(LoginRequiredMixin, ListView):
    model = BillType
    template_name = "split_bills_app/bill-type-list.html"

class BillTypeCreateView(LoginRequiredMixin, CreateView):
    model = BillType
    template_name = "split_bills_app/create.html"
    fields = ('name',)
    success_url = reverse_lazy('bill-type-list')

class BillTypeUpdateView(LoginRequiredMixin, UpdateView):
    model = BillType
    template_name = "split_bills_app/update.html"
    fields = ('name',)
    
    def get_success_url(self):
        return reverse_lazy('bill-type-list')

class BillTypeDeleteView(LoginRequiredMixin, DeleteView):
    model = BillType
    template_name = "split_bills_app/delete.html"
    success_url =reverse_lazy('bill-type-list')

#Bills Views
class BillsListView(LoginRequiredMixin, ListView):
    model = Bills
    template_name = "split_bills_app/bills-list.html"

class BillsCreateView(LoginRequiredMixin, CreateView):
    model = Bills
    fields = '__all__'
    template_name = "split_bills_app/create.html"
    success_url = reverse_lazy('bills-list')

class BillsUpdateView(LoginRequiredMixin, UpdateView):
    model = Bills
    template_name = "split_bills_app/update.html"
    fields = '__all__'
    def get_success_url(self):
        return reverse_lazy('bills-list')

class BillsDeleteView(LoginRequiredMixin, DeleteView):
    model = Bills
    template_name = "split_bills_app/delete.html"
    success_url = reverse_lazy('bills-list')

split_bills_app/templates/base_generic.html
{# Load the tag library#}
{% load bootstrap4 %}
{% load static%}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Split Bills</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="split_bills/split_bills_app/templates/cash.svg">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">    
      {% block menu%}
      <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" 
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'house-list' %}">Split Bills</a>
       {% if request.user.is_authenticated %} 
       <a href={% url 'logout' %}>Logout</a>
       {% else %}
       <a href={% url 'login' %}>Login</a>
       {% endif %}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a class='nav-link' href="{% url 'house-list' %}">Houses</a></li>
          <li class="nav-item"><a class='nav-link' href="{% url 'residents-list' %}">Residents</a></li>
          <li class="nav-item"><a class='nav-link' href="{% url 'bill-type-list' %}">Bill Type</a></li>
          <li class="nav-item"><a class='nav-link' href="{% url 'bills-list' %}">Bills</a></li>
          </ul>
        </div>
      </nav>
      {% endblock%}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

split_bills_app/templates/bill-type-list.html
{% extends "base_generic.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="row">
    <div class="col-xl-12">
        <div class="card bg-secondary shadow h-100">
            <div class="card-header bg-white border-0">
                <div class="row align-items-center">
                    <div class="col-8">
                        <h3 class="mb-0">List of Type Bill</h3>
                    </div>
                    <div class="col-4 text-right">
                        <a href="{% url 'bill-type-create' %}" class="btn btn-sm btn-success">New</a>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table align-items-center table-flush table-dark">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col"></th>                     
                    </tr>
                </thead>
                <tbody>
                    {% for billtype in billtype_list %}
                    <tr>
                        <td>{{ billtype }}</td>
                        <td class="text-right">
                            <div class="container">
                                {% buttons %}
                                <a role='button' class="btn btn-primary" href="{% url 'bill-type-update' billtype.cod_bill_type %}">Update</a>
                                <a role='button' class="btn btn-danger" href="{% url 'bill-type-delete' billtype.cod_bill_type %}">Delete</a>
                                {% endbuttons %}
                            </div>                            
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>
{% endblock %}

split_bills_app/templates/bills-list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="row">
    <div class="col-xl-12">
        <div class="card bg-secondary shadow h-100">
            <div class="card-header bg-white border-0">
                <div class="row align-items-center">
                    <div class="col-8">
                        <h3 class="mb-0">List of Bill</h3>
                    </div>
                    <div class="col-4 text-right">
                        <a href="{% url 'bills-create' %}" class="btn btn-sm btn-success">New</a>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table align-items-center table-flush table-dark">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">House</th>
                        <th scope="col">Type</th>
                        <th scope="col"></th>                     
                    </tr>
                </thead>
                <tbody>
                    {% for bills in bills_list %}
                    <tr>
                        <td>{{ bills }}</td>
                        <td>{{ bills.cod_house }}</td>
                        <td>{{ bills.cod_bill_type }}</td>
                        <td class="text-right">
                            <div class="container">
                                <a role='button' class="btn btn-primary" href="{% url 'bills-update' bills.cod_bills %}">Update</a>
                                <a role='button' class="btn btn-danger" href="{% url 'bills-delete' bills.cod_bills %}">Delete</a>
                            </div>                            
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>
{% endblock %}

split_bills_app/templates/create.html
{% extends "base_generic.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Create a New</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-success">Create</button>
            {% endbuttons%}
        </form>
    </div>
</div>
{% endblock %}

split_bills_app/templates/delete.html
{% extends "base_generic.html" %}
{% block content %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Delete House #{{object.id}}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                Are you sure you want to delete <strong>{{ object }}</strong> ?
            </div>
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </div>
</div>
{% endblock %}

split_bills_app/templates/house-list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="row">
    <div class="col-xl-12">
        <div class="card bg-secondary shadow h-100">
            <div class="card-header bg-white border-0">
                <div class="row align-items-center">
                    <div class="col-8">
                        <h3 class="mb-0">List of Houses</h3>
                    </div>
                    <div class="col-4 text-right">
                        <a href="{% url 'house-create' %}" class="btn btn-sm btn-success">New</a>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table align-items-center table-flush table-dark">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">Nick Name</th>
                        <th scope="col">Adress</th>  
                        <th scope="col"></th>                     
                    </tr>
                </thead>
                <tbody>
                    {% for house in houses %}
                    <tr>
                        <td>{{ house.nick_name }}</td>
                        <td>{{ house.adress }}</td>
                        <td class="text-right">
                            <div class="container">
                                <a role='button' class="btn btn-primary" href="{% url 'house-update' house.cod_house %}">Update</a>
                                <a role='button' class="btn btn-danger" href="{% url 'house-delete' house.cod_house %}">Delete</a>
                            </div>                            
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>
{% endblock %}

split_bills_app/templates/residents-list.html
{% extends "base_generic.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="row">
    <div class="col-xl-12">
        <div class="card bg-secondary shadow h-100">
            <div class="card-header bg-white border-0">
                <div class="row align-items-center">
                    <div class="col-8">
                        <h3 class="mb-0">List of Residents</h3>
                    </div>
                    <div class="col-4 text-right">
                        <a href="{% url 'residents-create' %}" class="btn btn-sm btn-success">New</a>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table align-items-center table-flush table-dark">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">E-mail</th>  
                        <th scope="col"></th>                     
                    </tr>
                </thead>
                <tbody>
                    {% for resident in residents_list %}
                    <tr>
                        <td>{{ resident.name }}</td>
                        <td>{{ resident.email }}</td>
                        <td class="text-right">
                            <div class="container">                               
                                <a role='button' class="btn btn-primary" href="{% url 'residents-update' resident.cod_resident %}">Update</a>
                                <a role='button' class="btn btn-danger" href="{% url 'residents-delete' resident.cod_resident %}">Delete</a>                                 
                            </div>                            
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>
{% endblock %}

split_bills_app/templates/update.html
{% extends "base_generic.html" %}
{% load bootstrap4 %}
{% block content %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Update #{{ object }}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form%}
            {% buttons %}
                <button type="submit" class="btn btn-success">Update</button>
            {% endbuttons %}
        </form>
    </div>
</div>
{% endblock %}